substitutions:
  devicename: office
  upper_devicename: Office

esphome:
  name: $devicename
  platform: ESP8266
  board: huzzah

<<: !include common/device_base.yaml

# packages:
#   device_base: !include common/device_base.yaml

dallas:
  - pin: GPIO4

sensor:
  - platform: uptime
    name: "${upper_devicename} Uptime Sensor"
  - name: "Garden Temperature"
    platform: dallas
    address: 0xDB3C01B556748428
  - platform: dht
    pin: GPIO12
    temperature:
      name: "${upper_devicename} Temperature"
    humidity:
      name: "${upper_devicename} Humidity"

switch:
  - name: "${upper_devicename} Feather LED"
    id: led
    platform: gpio
    pin: 0
    inverted: yes