substitutions:
  devicename: office
  upper_devicename: Office

esphome:
  name: $devicename
  platform: ESP8266
  board: huzzah

web_server:
  port: 80

packages:
  device_base: !include common/device_base.yaml

dallas:
  - pin: GPIO4

sensor:
  - platform: dht
    pin: GPIO12
    temperature:
      name: "${upper_devicename} Temperature"
    humidity:
      name: "${upper_devicename} Humidity"
    update_interval: 60s
  - platform: dallas
    address: 0xDB3C01B556748428
    name: "Garden Temperature"
    
switch:
  - name: "${upper_devicename} Feather LED"
    id: led
    platform: gpio
    pin: 0
    inverted: yes