wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase
  domain: !secret domain

  ap:
    ssid: "${devicename}.fb"
    password: !secret wifi_fallback_passphrase

mqtt: 
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: !secret mqtt_port
  discovery: True
  discovery_retain: True
  discovery_prefix: "homeassistant"
  topic_prefix: "${devicename}"

captive_portal: {}
logger: {}

ota:
  password: !secret ota_password

web_server:
  port: 80
